# smoothpaper configuration file

# path your wallpapers are stored in
wallpapers = "~/Pictures"
# alternatively, you can specify a list of directories to search for wallpapers
# wallpapers = ["~/Pictures/wallpapers", "~/Downloads/wide_walls"]

# whether the files should be shuffled or not. If you do not shuffle, the files will be 
# displayed in the order they are found which is dependent on the filesystem. I'm not
# sure why you'd want to do this, but it's an option.
shuffle = true

# the mode to scale the images. Options are
#
#   "vertical": scales the image to fit vertically; on widescreens this might result in
#               bars on the side if the wallpaper has a less wide aspect ratio. On other
#               displays this might mean cropping the sides if the wallpaper has a wider
#               aspect ratio than the screen.
#
# "horizontal": scales the image to fit horizintally; on widescreens this might result in
#               cropping the top and bottom of the image. On a 4:3 or 16:9 screen this might
#               result in bars on the top and bottom if the aspect ratio of the wallpaper
#               is wider than your screen.
#
#  "stretched": will stretch the image in both directions to fit your screen. This means
#               that if the image does not match your screen's aspect ratio, it will be
#               distorted.
#
#     "center": will center the image on the screen. This means that if the image does not match
#               your screen's aspect ratio, it will be cropped on the sides or top and bottom.
#               depending on the mode you choose, or it might just be centered with bars on the sides
#               or top and bottom.
scale_mode = "horizontal"

# the speed at which the images fade in and out, in seconds.
fade_speed = 5

# the delay between images, in seconds. Must be an integer.
delay = 300

# frames per second for the opengl renderer. This is the maximum number of frames per second
# that will be rendered. Lowering this value will reduce CPU usage, but may cause the animation 
# to be less smooth.
framerate_limit = 60

# whether to display debug information or not.
debug = false
